window.toolsData = [
    { id: 1, title: "Pulse Wealth Tracker", link: "/finance/pulse-neural-wealth-architect", category: "finance" },
    { id: 2, title: "Vestiq Equity Simulator", link: "/finance/vestiq-quantum-equity-vesting-simulator", category: "finance" },
    { id: 3, title: "RunwayZero", link: "/finance/runwayzero-tool", category: "finance" },
    { id: 4, title: "SubsLayer", link: "/finance/subslayer-expense-tracker", category: "finance" },
    { id: 5, title: "TokenForge", link: "/dev/tokenforge-sandbox", category: "dev" },
    { id: 6, title: "BranchWeaver", link: "/dev/branchweaver-git-simulator", category: "dev" },
    { id: 7, title: "RegexDrill", link: "/dev/regexdrill-execution-profiling-engine", category: "dev" },
    { id: 8, title: "SchemaSynth", link: "/dev/schemasynth", category: "dev" },
    { id: 9, title: "VelocityRead", link: "/studyzone/velocityread-tool", category: "student" },
    { id: 10, title: "DeepworkWeaver", link: "/studyzone/deepwork-weaver", category: "student" },
    { id: 11, title: "IdeahaRvest", link: "/studyzone/ideaharvest", category: "student" },
    { id: 12, title: "ChronoBlock", link: "/studyzone/chronoblock-tactile-time-allocation-matrix", category: "student" },
    { id: 13, title: "NeuroPulse", link: "/braintraining/neuropulse-dual-n-back", category: "brain" },
    { id: 14, title: "BiasBreaker", link: "/braintraining/biasbreaker-cognitive-bias-forensic-simulator", category: "brain" },
    { id: 15, title: "NeuroFlex", link: "/braintraining/neuroflex-engine", category: "brain" },
    { id: 16, title: "CircadiaSynic", link: "/health/circadiasync-alignment-engine", category: "health" },
    { id: 17, title: "MacroShift", link: "/health/macroshift-Tool", category: "health" },
    { id: 18, title: "PranaPace", link: "/health/pranapace-neural-breath-sync", category: "health" },
    { id: 19, title: "StimCurve", link: "/health/stimcurve-tool", category: "health" },
    { id: 20, title: "StressShield", link: "/health/stressshield-tool", category: "health" },
    { id: 21, title: "DeployNexus", link: "/dev/deploynexus-simulation-engine", category: "dev" },
    { id: 23, title: "PDF Protect", link: "/pdfmagic/pdf-security", category: "pdf" },
    { id: 24, title: "ImageFormat Converter", link: "/Imagelab/image-format-converter", category: "image" },
    { id: 25, title: "FireCalc", link: "/finance/fire-calculator", category: "finance" },
    { id: 26, title: "Cognitive Visual Trainer", link: "/braintraining/cognitive-visual-trainer", category: "brain" },
    { id: 27, title: "Calorie Calculator", link: "/health/calorie-calculator", category: "health" },
    { id: 28, title: "Loan Calculator", link: "/finance/loan-emi-calculator", category: "finance" },
    { id: 29, title: "Compound Interest", link: "/finance/compound-interest-calculator", category: "finance" },
    { id: 30, title: "Take Home Pay", link: "/finance/take-home-pay-calculator", category: "finance" },
    { id: 31, title: "Bill Splitter & Tip Calculator", link: "/finance/tip-calculator", category: "finance" },
    { id: 32, title: "DebtSlayer", link: "/finance/debt-payoff-calculator", category: "finance" },
    { id: 33, title: "SalaryLens", link: "/finance/salary-lens", category: "finance" },
    { id: 34, title: "Json Formatter", link: "/dev/json-formatter", category: "dev" },
    { id: 35, title: "Base64 Encoder & Decoder", link: "/dev/base64-encoder-decoder", category: "dev" },
    { id: 36, title: "Number System Converter", link: "/dev/number-converter", category: "dev" },
    { id: 37, title: "CSS Shadow & Gradient Generator", link: "/dev/css-shadow-gradient-generator", category: "dev" },
    { id: 38, title: "Color Palette Generator", link: "/dev/color-tokenizer", category: "dev" },
    { id: 39, title: "CronCraft", link: "/dev/croncraft", category: "dev" },
    { id: 40, title: "GradeForge", link: "/studyzone/grade-calculator", category: "student" },
    { id: 41, title: "Word Counter", link: "/studyzone/word-counter", category: "student" },
    { id: 42, title: "CaseForge", link: "/studyzone/case-converter", category: "student" },
    { id: 43, title: "TypeForge", link: "/studyzone/typing-speed-test", category: "student" },
    { id: 44, title: "Writing Clarity", link: "/studyzone/writing-clarity-analyzer", category: "student" },
    { id: 45, title: "FlashMatrix", link: "/studyzone/spaced-repetition-flashcards", category: "student" },
    { id: 46, title: "Exam Timer", link: "/studyzone/exam-timer", category: "student" },
    { id: 47, title: "ReflexLab", link: "/braintraining/reaction-time-test", category: "brain" },
    { id: 48, title: "Click Speed Test", link: "/braintraining/click-speed-test", category: "brain" },
    { id: 49, title: "Sequence Memory Test", link: "/braintraining/memory-test", category: "brain" },
    { id: 50, title: "IQ Test", link: "/braintraining/iq-test", category: "brain" },
    { id: 51, title: "Dual N-Back", link: "/braintraining/dual-n-back-training", category: "brain" },
    { id: 52, title: "BMI Calculator", link: "/health/bmi-calculator", category: "health" },
    { id: 53, title: "Age Calculator", link: "/health/age-calculator", category: "health" },
    { id: 54, title: "Water Intake Calculator", link: "/health/water-intake-calculator", category: "health" },
    { id: 55, title: "Sleep Cycle Calculator", link: "/health/sleep-cycle-calculator", category: "health" },
    { id: 56, title: "Health Score Calculator", link: "/health/health-score-calculator", category: "health" },
    { id: 57, title: "PDF Merger", link: "/pdfmagic/pdf-merge", category: "pdf" },
    { id: 58, title: "PDF Compressor", link: "/pdfmagic/pdf-compressor", category: "pdf" },
    { id: 59, title: "PDF Splitter", link: "/pdfmagic/pdf-splitter", category: "pdf" },
    { id: 60, title: "PDF Text Extractor", link: "/pdfmagic/pdf-text-extractor", category: "pdf" },
    { id: 61, title: "PDF Watermark", link: "/pdfmagic/watermark", category: "pdf" },
    { id: 62, title: "Image Compressor", link: "/Imagelab/image-compressor", category: "image" },
    { id: 63, title: "Image Resizer", link: "/Imagelab/resizer-crop-tool", category: "image" },
    { id: 64, title: "Color Palette Extractor", link: "/Imagelab/color-palette-extractor", category: "image" }
];
